import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { GameProvider } from '../contexts/gameContext'
import '@rainbow-me/rainbowkit/styles.css';

import {
  getDefaultWallets,
  RainbowKitProvider,
} from '@rainbow-me/rainbowkit';
import { configureChains, createConfig, WagmiConfig } from 'wagmi';
import {
  bsc,
  bscTestnet,
  goerli,
} from 'wagmi/chains';
import { alchemyProvider } from 'wagmi/providers/alchemy';
import { jsonRpcProvider } from 'wagmi/providers/jsonRpc';
import { publicProvider } from 'wagmi/providers/public';

const { chains, publicClient } = configureChains(
  [goerli, bsc, bscTestnet],
  [
    alchemyProvider({ apiKey: process.env.NEXT_PUBLIC_ALCHEMY_ID! }),
    jsonRpcProvider({
      rpc: (chain) => { return { http: `${process.env.NEXT_PUBLIC_BLOCKCHAIN_RPC}` };
    },
  }),
    publicProvider()
  ]
);

const { connectors } = getDefaultWallets({
  appName: 'Xance',
  projectId: 'Xance',
  chains
});

const wagmiConfig = createConfig({
  autoConnect: true,
  connectors,
  publicClient
})

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WagmiConfig config={wagmiConfig}>
          <RainbowKitProvider chains={chains}>
            <GameProvider>
              {children}
            </GameProvider>
          </RainbowKitProvider>
        </WagmiConfig>
      </body>
    </html>
  )
}
